name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Provisioning Profiles
      run: |
        echo "*** before copy provisioning files"
        #ls -l ~/Library/MobileDevice/Provisioning\ Profiles
        ditto provisioning/* ~/Library/MobileDevice/Provisioning\ Profiles/
        echo "*** after copy provisioning files"
        ls -l ~/Library/MobileDevice/Provisioning\ Profiles
# /Users/chenchang/Library/MobileDevice/Provisioning Profiles*: No such file or directory
#chenchang@chenchangdeiMac Swiftris % cp ~/Library/MobileDevice/Provisioning\ Profiles/* provisioning
#chenchang@chenchangdeiMac Swiftris % ls -l provisioning 
#total 16
#-rw-r--r--  1 chenchang  staff  7438  9  4 06:30 ffa23e17-ffc0-4bd3-9558-8b2b561ac12e.mobileprovision
#chenchang@chenchangdeiMac Swiftris % git add provisioning/ffa23e17-ffc0-4bd3-9558-8b2b561ac12e.mobileprovision 
#chenchang@chenchangdeiMac Swiftris % git commit -m "Add provision profiles"
#[master 29765cb] Add provision profiles
#
    - name: Build
      run: |
        xcodebuild clean
        xcodebuild

#    - uses: Apple-Actions/import-codesign-certs@v1
#      with:
#        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
#        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
#    - uses: Apple-Actions/download-provisioning-profiles@v1
#      with:
#        bundle-id: codes.orj.Example-iOS
#        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
#        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
#        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
#    - name: "#️⃣ Generate Build Number"
#      id: buildnumber
#      uses: einaregilsson/build-number@v2
#      with:
#        token: ${{ secrets.github_token }}
#    - run: ./Build
#    - uses: Apple-Actions/upload-testflight-build@master
#      with:
#        app-path: .build/Artifacts/Example-iOS.ipa/Example-iOS.ipa
#        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
#        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
#        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
